### ISSUE TITLE
Not working since a Gamdom update

### ISSUE THREAD

**Issue by mpremiumajl** [douglasouza/gambScripts#1]
Soooo, I used your script, everything ok, and after a gamdom recent update if I reduce Firefox to taskbar I don't longer get rains.
Fix please, you're the only that doesnt steal coins.

**Comment by douglasouza** [comment]
What specific script is not working properly? The rain one? It's been a while since I've entered Gamdom for the last time, that's why we're not updating the scripts anymore.

**Comment by mpremiumajl** [comment]
rain-2.0.js and rain.js

Seems that gamdom after making some tests actually discovered rain scripts(there are some apart from you, but your was the best, at least for me) and made that if you stay so much time with the browser in background(in taskbar) it disconnects from chat and you don't get messages until you get reconnected.

Probably there's a way to avoid the "outside-tab" detection, but I don't reach that javascript level, I know a little bit but I'm not javascript "pro", I just know some things.

**Comment by douglasouza** [comment]
Ok, I think I understand what's happening. I'll try to take a look at it when I have some spare time.

**Comment by mpremiumajl** [comment]
Ok, thx

**Comment by douglasouza** [comment]
The quick fix that I found is to open one browser window with only the Gamdom tab open. That way the tab is always active and the chat doesn't go inactive. I could try and take a look at it with multiple tabs, but I don't have the time now and I can't assure I'll find a solution for this.
