### ISSUE TITLE
Gamdom detected your script

### ISSUE THREAD

**Issue by mpremiumajl** [douglasouza/gambScripts#2]
Soooo Gamdom detected all gamdom rain scripts and they give 24h bans for using them.
Your script is one of the ones that got detected.

**Comment by douglasouza** [comment]
Yeah, it sucks but I can't do much from my side. It's up to them now.
I don't know why they did this. My script doesn't steal coins or does anything wrong on the site. It just warns you that there's a rain going on. Maybe they implemented a generic way and just ban everyone that uses one, no matter what it does.

**Comment by mpremiumajl** [comment]
Nope, it's the rain scripts, because the message is:

"You are still muted for another 24h. Reason: using a rain notification script is forbidden"(and if you're muted you can't get rains nor chat, you can only bet and I think that withdraw).

IDK exactly how they detect it but Is think it's by variables, by clicks or whatever. So bad that the main javascript that runs gamdom(and where probably the detection occurs) is obfuscated, with variable names and functions names changed for random names and with like 90,000 lines of code if you try to "deobfuscate" it. They probably ban because: "oh no I win millions of dollars monthly in skins but I can't lose only like $500 for rain scripts...That hirts my oocket, because I want to be $500 more rich" or something like that
